"""Relationship between cat and human created

Revision ID: 21104e97db14
Revises: 8c6ffbd1cab7
Create Date: 2022-05-11 14:26:03.151948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21104e97db14'
down_revision = '8c6ffbd1cab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('human_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cat', 'human', ['human_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cat', type_='foreignkey')
    op.drop_column('cat', 'human_id')
    # ### end Alembic commands ###
